name: Build ESP-IDF project

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up ESP-IDF
        uses: espressif/install-esp-idf-action@v1
        with:
          version: v6.1

      - name: Build
        run: |
          idf.py build